### ISSUE TITLE
🧪 [Experiment] SizerBase class for GridSplitter + ContentSizer + PropertySizer

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#101]
# Approved from Discussion #96

## Problem Statement (copied from Discussion):

We have various types of experience which need 'gripper bars' in order to provide a user with the ability to resize/drag an area of UI around in an application. These all have similar visual and behavior cues, but may require different logic to manipulate the underlying UI structure.

## Overview

This experiment adds the following components:

- **SizerBase** an abstract base class to centralize logic around input, visuals, and accessibility.
- **GridSplitter** knows how to manipulate a `Grid`'s rows/columns
- **ContentSizer** knows how to manipulate the `Width`/`Height` of any `FrameworkElement`
- **PropertySizer** knows how to directly manipulate any bound `double` value

![SizerBase](https://user-images.githubusercontent.com/9866362/233377618-5087ba12-4e41-461b-ba24-b172f98661f2.gif)

## Using

You can try it out via the NuGet Packages here:

- UWP: https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-MainLatest/NuGet/CommunityToolkit.Uwp.Controls.Sizers
- WinUI 3: https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-MainLatest/NuGet/CommunityToolkit.WinUI.Controls.Sizers

Read more about [Preview Packages here](https://aka.ms/wct/wiki/previewpackages).

This control has moved from Labs to the new [main repo](https://github.com/CommunityToolkit/Windows).

CommunityToolkit members can also try it out with Codespaces.

```[tasklist]
## TO DO
- [x] Fix Mouse Extension Cursor change for WASM (was working at one point, think messed up conditional logic again) See #208 
- [x] Add some enum/bool for auto hiding the splitter and having it appear on hover (think size should be consistent, so just an animation?)
- [x] WinUI 3 may behave oddly - see https://github.com/microsoft/microsoft-ui-xaml/issues/6847
- [x] Orientation Property #388
```

Not all these items are required to submit a PR. This list is here to help track what is remaining to implement before a technical review and discussion of moving into the main repository can occur.

```[tasklist]
## Implementation Requirements
- [x] Working Prototype
- [x] Feature Complete
- [ ] Documentation
  - [ ] SizerBase
  - [x] ContentSizer
  - [x] PropertySizer
  - [ ] GridSplitter
- [ ] Samples
  - [ ] SizerBase
  - [x] ContentSizer
  - [x] PropertySizer
  - [x] GridSplitter
- [ ] Tests
- [ ] Community Feedback / Usage Testimonies
```

```[tasklist]
## Tested Platforms
- [x] UWP
- [x] WinAppSDK / WinUI 3
- [x] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK
```

These items can sometimes be done ahead of time, but are usually started and completed after all implementation details are finished.

```[tasklist]
## Technical Review
- [ ] Accessibility Audit
- [ ] API/Naming Review
- [ ] Code Quality/Style
- [ ] Dependency Review
- [ ] Design/Style Review
- [ ] Final Approval
```

**Comment by michael-hawker** [comment]
Figured out what was going on with the cursor not properly updating when the Orientation is Horizontal (like in the sample) - regression from current Toolkit version.

It's this code here:

https://github.com/CommunityToolkit/Labs-Windows/blob/9045236e77884e6c5c9fccb261e390001c93d4ec/labs/SizerBase/src/SizerBase.Properties.cs#L98-L110

Since we set the value of the dependency property, when the initial pass run on load sets it to `SizeWestEast`. Then the detection logic runs and `Orientation` is changed to `Horizontal`, but the set gets ignored the 2nd time as the prop has been set...

Think this was abstracted in the old code as the inner class held that info.

Here, I think we need to just have the private value tracking what the cursor should be and leave the Cursor property for overrides? Will think about it more and get back to it as a separate fix.

**Comment by michael-hawker** [comment]
Behavior for WindowsAppSDK is looking good now on 1.3, will push a PR up shortly, also trying to fix the Cursor orientation bug number #388.

**Comment by alexfalconflores** [comment]
The styling of this control in UWP does not look the same as the styling of WASM or the toolkitlabs.dev page.
In the UWP version it shows an old design.

![Screenshot 2023-06-28 194942](https://github.com/CommunityToolkit/Labs-Windows/assets/75406302/c7a407d8-0de6-4def-9487-c230c986a353)

UWP (xmlns:labs="using:CommunityToolkit.Labs.WinUI" )

![Screenshot 2023-06-28 194959](https://github.com/CommunityToolkit/Labs-Windows/assets/75406302/89487562-9922-4f16-b7bb-a9fd493a4f5b)

toolkitlabs.dev

**Comment by michael-hawker** [comment]
@alexfalconflores are you using [the new package (`CommunityToolkit.Uwp.Controls.Sizers`)](https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-MainLatest/NuGet/CommunityToolkit.Uwp.Controls.Sizers/overview/8.0.0-beta.3) from the [Windows repo](https://github.com/CommunityToolkit/Windows)?

**Comment by alexfalconflores** [comment]
![Screenshot 2023-07-01 171827](https://github.com/CommunityToolkit/Labs-Windows/assets/75406302/2fda42bd-5cf6-47c8-9731-4cdcc4ff9c13)
I'm using this

**Comment by niels9001** [comment]
> ![Screenshot 2023-07-01 171827](https://github.com/CommunityToolkit/Labs-Windows/assets/75406302/2fda42bd-5cf6-47c8-9731-4cdcc4ff9c13)
> I'm using this
> 
> https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json

@alexfalconflores Looks like you are using the `Sizers` from Labs.. we have recently moved these to the main Toolkit and made any updates there.

So, instead of using CommunityToolkit.**Labs**.Uwp.Sizers use the CommunityToolkit.Uwp.Sizers package.. it's on the same preview Nuget feed!

**Comment by alexfalconflores** [comment]
Thanks for the help @niels9001 and @michael-hawker. The new control design looks great. Keep it up.

Do you know when UWP will support .net 7 or 8?

CommunityToolkit.Uwp.Controls.Sizers   . nuget release

![Screenshot 2023-07-04 125946](https://github.com/CommunityToolkit/Labs-Windows/assets/75406302/a78c125d-4d23-4fcc-9c9f-0c4b4bfde467)
![Screenshot 2023-07-04 130047](https://github.com/CommunityToolkit/Labs-Windows/assets/75406302/27192c4b-0e30-48c9-ad60-62b0524c0011)

**Comment by michael-hawker** [comment]
> Do you know when UWP will support .net 7 or 8?

@alexfalconflores see discussions [here](https://github.com/microsoft/WindowsAppSDK/discussions/1055) and [here](https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483) - if you need the latest .NET then you'd want to port to WinUI 3 (which is what we're making all our components work with both to make it easy to do). If you just need newer language features for C#, look at [PolySharp](https://github.com/Sergio0694/PolySharp).

**Comment by michael-hawker** [comment]
This was shipped in the [8.0 Release](https://github.com/CommunityToolkit/Windows/releases/tag/v8.0.230907), please update to use that version of the component. Any further issues/requests should start in the main repository.

**Comment by Fabi12345** [comment]
So I always have to point the cursor to the center of that splitter despite it requires the whole space along the container? And the normal GridSplitter belongs to a deprecated package, but has no hover function, sigh, WinUI has become a mess.

**Comment by niels9001** [comment]
> So I always have to point the cursor to the center of that splitter despite it requires the whole space along the container? And the normal GridSplitter belongs to a deprecated package, but has no hover function, sigh, WinUI has become a mess.

@Fabi12345 This issue is closed, so it might not reflect the latest changes.

- You do not have to point at the center.. you can point anywhere on the control.

https://github.com/user-attachments/assets/19845631-640c-463e-8c4d-d59b6b685fcc

- `GridSplitter` belongs to the Windows Community Toolkit 8.x packages. Those are not deprecated at all: https://www.nuget.org/packages/CommunityToolkit.WinUI.Controls.Sizers

- What do you mean with 'hover function'? There's a hover state in the sizer controls in case you want to customize that!

You can install the Windows Community Gallery app from the Store here, it has all of the information you'd need: https://www.microsoft.com/store/productId/9NBLGGH4TLCQ
