### ISSUE TITLE
Setup CI Infrastructure

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#13]
Pooling from various discussions, there's a bit of stuff we want to have running in the CI so all experiments are automatically validated from tests provided by the developers. We should also include our template to ensure all new experiences should be functional out-of-the-box (and to validate CI/pipeline with a known component).

- [ ] CI should build a NuGet package for every experiment
  - [ ] Should push to our DevOps Artifact Feed: https://dev.azure.com/dotnet/CommunityToolkit/_packaging?_a=feed&feed=CommunityToolkit-Labs
- [x] CI should run all unit tests
- ~CI should run all UI tests (WinAppDriver): https://github.com/Microsoft/WinAppDriver/wiki/WinAppDriver-in-CI-with-Azure-Pipelines~
- [x] CI should run build the Template project
  - [x] CI should run the ~UI and~ Unit tests for the Template project
- [x] CI should build the all encompassing sample app
  - [ ] P2: Auto-publish to the store?

**Comment by Arlodotexe** [comment]
@michael-hawker Do we want to close this off?

**Comment by michael-hawker** [comment]
@Arlodotexe yup, will close this off we have #133 for auto-versioning. And #339 brings up about the store, though we may just blend things into the main Toolkit sample app.
