### ISSUE TITLE
Update version of Uno being used.

### ISSUE THREAD

**Issue by mrlacey** [CommunityToolkit/Labs-Windows#174]
Labs projects are currently targetting Uno 4.2, but 4.3 is out (and 4.4 is due soon)

Uno.UI (v4.2.6) includes a bug that is blocking  #97 
However, updating to v 4.3.8 (the latest stable version) causes `XamlNamedPropertyRelayGenerator` to fail / fall silently--presumably due to the change in the way that Uno uses SourceGenerators.

Also worth confirming/investigating is that as Uno now uses the same sort of Source Generators (SGs) as Labs, does this have any issues for deterministic order? i.e. The Labs SGs rely on the output of the Uno SGs. Can they always be guaranteed to run in the desired order?

Adding a strategy & process for how and when to update to newly released Uno versions should also be planned. Such a plan would naturally extend to all dependencies too.

**Comment by Arlodotexe** [comment]
Looks like only the WPF is having issues when upgrading Uno.

I've tried to update us to the latest version of the Uno templates, but ran into this issue
- https://github.com/unoplatform/uno/issues/9380

**Comment by Arlodotexe** [comment]
Closed in #258
