### ISSUE TITLE
Can't build ProjectTemplate solution WindowsAppSDK head locally

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#188]
1. Clone `main`
2. Open ProjectTemplate.sln in template\lab folder
3. Try and run tests

Get errors from registry source generators for WinAppSDK:
![image](https://user-images.githubusercontent.com/24302614/177854566-cb97c2e8-3bf9-4c17-a7c1-0db933370966.png)

Weird thing is that our CI is passing which is running these tests... 🤔

We need to ensure:
- [ ] ProjectTemplate.sln builds locally
- [ ] We understand why this failed locally and not in CI
- [ ] Write a test case which can help us guard against this breaking in the future

Not sure if #185 or #167 introduced this or earlier, will check after lunch to try and find last known good point for comparison.

**Comment by Arlodotexe** [comment]
> I documented this better here now: https://github.com/CommunityToolkit/Labs-Windows/tree/main/template#long-paths
> 
> Do we think that's enough for now? @LalithaNadimpalli @Arlodotexe?

Since we have a solution, and it's documented now, I'll be closing this off.
