### ISSUE TITLE
Add more Sample Option Attributes

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#207]
Related #149 

Realized as we've been building more samples, that just having `bool` and `multi-choice` as our options is a bit limiting, so wanted to list out some other simple scenarios for `ToolkitSample*OptionAttribute`s we may want in the future:

| Name | Parameters | Description |
|--------|---------------|----------------------|
| `ToolkitSampleCommandOptionAttribute` | `label` + `nameof(SomeMethodOnSampleClass)` | Creates a `Button` with `label` content which will execute the command when clicked |
| `ToolkitSampleTextOptionAttribute` | `title` (as normal) + `placeholder` | Creates a `TextBox` with `placeholder` text, allows user to type freeform text |
| `ToolkitSampleSliderOptionAttribute` | `min` + `max` + `step` + `initial` | Creates a `Slider` |

We may also want a flag for MultiChoice to change whether it's radio buttons or a combobox?

We can always refer to [our existing sample methods for ideas](https://github.com/CommunityToolkit/WindowsCommunityToolkit/tree/main/Microsoft.Toolkit.Uwp.SampleApp#2-binding-text).

**Comment by michael-hawker** [comment]
Also found an issue trying to TwoWay bind to a `ToolkitSampleBoolOption` value. Uno throws an error in its XAML source generator that it can't find the property.

**Comment by Arlodotexe** [comment]
> Also found an issue trying to TwoWay bind to a `ToolkitSampleBoolOption` value. Uno throws an error in its XAML source generator that it can't find the property.

Thanks, we'll get that fixed up when we move focus back to Labs again.
