### ISSUE TITLE
🧪 [Experiment] StackedNotificationsBehavior for InfoBar

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#210]
# Approved from Toolkit
See previous work here:

- https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4194
- https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4399

FYI @vgromfeld

## Problem Statement (copied from Discussion):

The `InAppNotification` control is automatically hidden after the expiration of the notification duration. The durations we are hardcoding in our applications may not be long enough to allow the users to fully read the message. We should have a way to keep the notification visible for a longer time if the user wants/needs it.

## Overview

This experiment adds the following components:

- **StackedNotificationsBehavior** a behavior for the WinUI `InfoBar` control that provides a message queue.

## Using

You can try it out via the NuGet Packages here:

- UWP: https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-Labs/NuGet/CommunityToolkit.Labs.Uwp.StackedNotificationsBehavior
- WinUI 3: https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-Labs/NuGet/CommunityToolkit.Labs.WinUI.StackedNotificationsBehavior

Read more about [Preview Packages here](https://aka.ms/wct/wiki/previewpackages).

CommunityToolkit members can also try it out with Codespaces.

## TO DO
- [ ] Do we need an option to change ordering behavior of incoming messages (i.e. show newest ones before older ones vs. in received order?)
- [ ] Replace button in example (see #207)
- [ ] Show duration example (see #207)

## Implementation Requirements

Not all these items are required to submit a PR. This list is here to help track what is remaining to implement before a technical review and discussion of moving into the main repository can occur.

- [x] Working Prototype
- [ ] Feature Complete
- [ ] Documentation
- [ ] Samples
- [ ] Tests
- [ ] Community Feedback / Usage Testimonies

## Tested Platforms

- [x] UWP
- [x] WinAppSDK / WinUI 3
- [x] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

## Technical Review

These items can sometimes be done ahead of time, but are usually started and completed after all implementation details are finished.

- [ ] Accessibility Audit
- [ ] API/Naming Review
- [ ] Code Quality/Style
- [ ] Dependency Review
- [ ] Design/Style Review
- [ ] Final Approval

**Comment by michael-hawker** [comment]
Oops, we need to make sure not to accidentally close our experiment tracking issues (well until they end up in the main Toolkit that is). I didn't think we had a 'fixes' keyword in the PR... @Arlodotexe did you close this manually?

**Comment by Arlodotexe** [comment]
Looks like the issue was closed automatically by the linked pull request

**Comment by michael-hawker** [comment]
Opened port with better samples/tests/migration improvements here: https://github.com/CommunityToolkit/Windows/pull/170

**Comment by michael-hawker** [comment]
This was shipped in the [8.0 Release](https://github.com/CommunityToolkit/Windows/releases/tag/v8.0.230907), please update to use that version of the component. Any further issues/requests should start in the main repository.
