### ISSUE TITLE
CI Permission issues in PRs from forks 

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#221]
### Describe the bug

When someone forks the repo and creates a PR, GitHub Actions doesn't run as expected. Instead, it throws errors at us such as:

- [`Resource not accessible by integration`](https://github.com/CommunityToolkit/Labs-Windows/runs/7441466327?check_suite_focus=true#step:12:29) in the `experiment` job.
- [`Error: No test report files were found`](https://github.com/CommunityToolkit/Labs-Windows/runs/7441466211?check_suite_focus=true#step:17:27) in the `Build-WinUI-2` and `Build-WinUI-3` jobs.

### Steps to reproduce

```text
1. Fork the repo
2. Create a new branch
3. Make some changes
4. Open a new PR, merging your forked repo branch back into `main` in the original repo.
5. Wait for CI to fail.
```

### Expected behavior

CI should pass if changes are valid

### Screenshots

![image](https://user-images.githubusercontent.com/9384894/180279373-09c0c868-5904-4bdb-9a55-163f8ec43499.png)

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Potentially helpful resources:
- https://github.com/actions/first-interaction/issues/10
-  https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

### Notes to assignees
We should be able to safely fix this by branching main and changing the `build.yml` there, forking the repo, and making a PR to that new branch. That'll cause it to run our modified `build.yml` against the forked branch.

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment]
According to the [docs](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), the value of `github.ref` in the context of a `pull_request` trigger is the branch which is being merged _into_ (the base), rather than the branch which is being merged (the fork).

I've confirmed this in #222, we'll need to use a different environment variable that tell us if the branch being merged is from a fork.

@michael-hawker Any feedback or direction? Since this changes when packages are auto-published.

**Comment by Arlodotexe** [comment]
This might be one of the fixes we're looking for: https://github.com/dorny/test-reporter/issues/168

**Comment by michael-hawker** [comment]
@Arlodotexe exactly the `github.ref` is only `refs/heads/main` when it's being merged into main. You can see that the step for pushing packages doesn't run on a pull request run from a prior [PR build here](https://github.com/CommunityToolkit/Labs-Windows/runs/7433507712?check_suite_focus=true):

![image](https://user-images.githubusercontent.com/24302614/180296333-fed86612-a21c-4517-abcb-68f20b124583.png)

So by adding the if condition to this it won't try and add the source and use the unavailable token.

**Comment by Arlodotexe** [comment]
@michael-hawker I understand that perfectly well. The problem is that it will only and always run if it's being merged _into_ main, regardless of where the branch being merged into it is from (inside the CommunityToolkit org, or from a fork).

We need the ability to differentiate when the branch _being merged_ into main is a fork or not.

**Comment by michael-hawker** [comment]
If need be, we can look at an alternate test reporter now that we're a public repo: #72

@Sergio0694 FYI, just in case you need to add it to the GitHub org.

**Comment by Arlodotexe** [comment]
After a lot of digging, it looks like we can do this by using 2 separate jobs: 1 that assumes an insecure context and runs builds, and a second that takes the result of the build and runs in a secure context, allowing us to write tags, make comments, report test results, etc.

https://securitylab.github.com/research/github-actions-preventing-pwn-requests
