### ISSUE TITLE
Add support for using .NET 6 with the WASDK 1.0 release

### ISSUE THREAD

**Issue by kmgallahan** [CommunityToolkit/Labs-Windows#244]
As per [this request](https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/3998#issuecomment-971609595) to create a tracking issue, and [this comment](https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/3998#issuecomment-963546873):

> Yeah WinUI 3/WASDK is still based on .NET 5 from their last release. So I'm not sure yet on the timing of a plan on migrating to .NET 6 yet, we just synced with their release for the last 1.0-preview3 finally. Once they support it though, we'll update our WinUI packages to match.

The `CommunityToolkit.WinUI` package needs to be updated to support .NET 6 as a target in order to use it with WASDK 1.0.

| Project | Release Date |
|-|-|
| .NET 6 | Nov 8 |
| WASDK 1.0 | Nov 16 |
| WCT v.next | ? |

**Comment by Arlodotexe** [comment]
@michael-hawker The WASDK projects in Labs have been using net6.0 since day 1, but there are new project which need to be updated to use .NET 6 (wpf, android/ios, etc).

Closing this for now.
