### ISSUE TITLE
Main Build Failing Suddenly

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#263]
### Describe the bug

Our main build started failing near the end of last week with this error message ([see run here](https://github.com/CommunityToolkit/Labs-Windows/runs/7862442896?check_suite_focus=true)):
```
"D:\a\Labs-Windows\Labs-Windows\Toolkit.Labs.All.sln" (Restore target) (1) ->
"D:\a\Labs-Windows\Labs-Windows\platforms\CommunityToolkit.Labs.Skia.Gtk\CommunityToolkit.Labs.Skia.Gtk.csproj" (_GenerateProjectRestoreGraph target) (9:5) ->
(CollectPackageDownloads target) -> 
  D:\a\Labs-Windows\Labs-Windows\platforms\CommunityToolkit.Labs.Skia.Gtk\CommunityToolkit.Labs.Skia.Gtk.csproj : error NU1505: Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: Microsoft.NETCore.App.Host.win-x64 [5.0.16], Microsoft.NETCore.App.Host.win-x64 [5.0.16], Microsoft.NETCore.App.Host.win-x64 [5.0.16], Microsoft.NETCore.App.Host.win-x64 [5.0.16].


"D:\a\Labs-Windows\Labs-Windows\Toolkit.Labs.All.sln" (Restore target) (1) ->
"D:\a\Labs-Windows\Labs-Windows\platforms\CommunityToolkit.Labs.Wasm\CommunityToolkit.Labs.Wasm.csproj" (_GenerateProjectRestoreGraph target) (11:5) ->
  D:\a\Labs-Windows\Labs-Windows\platforms\CommunityToolkit.Labs.Wasm\CommunityToolkit.Labs.Wasm.csproj : error NU1505: Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: Microsoft.NETCore.App.Host.win-x64 [5.0.16], Microsoft.NETCore.App.Host.win-x64 [5.0.16], Microsoft.NETCore.App.Host.win-x64 [5.0.16], Microsoft.NETCore.App.Host.win-x64 [5.0.16].
```

Not sure what may have suddenly caused this and if it's [related to this Twitter thread](https://twitter.com/jlaban/status/1559156738695233537).

### Steps to reproduce

```text
Run CI on main
```

### Expected behavior

Passes

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [X] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [X] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, but only if others can assist.

**Comment by Arlodotexe** [comment]
Useful information: https://github.com/dotnet/sdk/issues/24747

**Comment by michael-hawker** [comment]
Related to #256 as well.
