### ISSUE TITLE
[SettingsCard] BitmapIcon does not have MaxWidth

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Labs-Windows#286]
### Describe the bug

When settings a BitmapIcon, the icon itself scales to the existing space:

![image](https://user-images.githubusercontent.com/9866362/196400513-5b89a850-3bc4-434a-98f0-4bf8d2a3d986.png)

### Reproducible in sample app?

- [ ] This bug can be reproduced in the sample app.

### Steps to reproduce

Use the following XAML:

```xml
<labs:SettingsCard Description="Control if a feature is enabled or disabled" Header="Enable feature">
      <labs:SettingsCard.HeaderIcon>
            <BitmapIcon ShowAsMonochrome="False" UriSource="https://seeklogo.com/images/W/windows-11-icon-logo-6C39629E45-seeklogo.com.png"/>
      </labs:SettingsCard.HeaderIcon>
      <ToggleSwitch />
</labs:SettingsCard>
```

### Expected behavior

The Icon should be the same size as the IconFontSize.

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by michael-hawker** [comment]
We should probably figure out how we want to handle issues in Labs, as I don't think we want the issue list to be filled with these for each and every experiment. I figured we'd use discussions or comments on the experiment issue? It'd be nice if issues had threads like discussions do, so maybe on the discussion would be better? As then we could comment on them each and then mark them with reactions?
