### ISSUE TITLE
Project should be able to declare supported platforms/TFMs

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#298]
### Describe the bug

Projects created with the current project template are hardcoded to use [TargetFrameworks.props](https://github.com/CommunityToolkit/Labs-Windows/blob/main/common/Labs.TargetFrameworks.props), which globally affects all files.

We need a way to specify the TargetFrameworks for a project from the project itself, rather than from the global `TargetFrameworks.props` file.

This may be doable by making the [`TargetFrameworks`](https://github.com/CommunityToolkit/Labs-Windows/blob/ab42cc03c7dc709dd648cfcc5ebd619ef68a888e/common/Labs.MultiTarget.props#L9-L16) conditional.

```xml
<!-- Example only -->
<PropertyGroup Condition="$(IsWasm) = 'true'">
  <TargetFrameworks>$(TargetFrameworks);$(WasmTargetFramework)</TargetFrameworks>
</PropertyGroup>

<PropertyGroup Condition="$(IsUwp) = 'true'">
  <TargetFrameworks>$(TargetFrameworks);$(UwpTargetFramework)</TargetFrameworks>
</PropertyGroup>

(...etc)
```
A developer can use these variable as flags at the top of the `csproj` for their Sample/Library project.

Sidenote: It's not clear if this is fully supported in MSBuild/Visual Studio.

To handle this in the "All projects" solution, we need to modify the [DiscoverSamples.ps1](https://github.com/CommunityToolkit/Labs-Windows/blob/ab42cc03c7dc709dd648cfcc5ebd619ef68a888e/DiscoverSamples.ps1) script to check discovered projects for the existing `IsWasm`, `IsUwp`, etc., properties to determine if it should be referenced by the sample head. Experiment projects do not use these properties yet, so they'll need to be added as needed.

### Steps to reproduce

```text
n/a
```

### Expected behavior

Project should be able to declare supported platforms/TFMs

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by michael-hawker** [comment]
Note from discussion for #301 (which may only support UWP initially), if a project doesn't support the Windows App SDK, then we shouldn't try to build nor spit out a `.WinUI.` NuGet package.
