### ISSUE TITLE
Enforce code styling and editor config

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#33]
The Labs repo is using default settings for code styling and `.editorconfig`. We need to bring in the `.editorconfig` and other code styling analyzers from the main repo.

**Comment by Jay-o-Way** [comment]
FYI: the nugget wasn't updated for a while, but v3.2311.2 has been published about two hours ago
https://github.com/Xavalon/XamlStyler/issues/429#issuecomment-1809602637
