### ISSUE TITLE
Remove "Labs" moniker from generated "All Component" solution

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#399]
## Background
The "All Component" solution refers to the solution file generated by [GenerateAllSolution.ps1](https://github.com/CommunityToolkit/Labs-Windows/blob/3bc27fd6ad50c15aaaf3d067fe5fcb5535dd1b6c/common/GenerateAllSolution.ps1).

## Problem
The script generates the `Toolkit.Labs.All.sln` file, and a number of things that reference it reside inside the `./common` folder. This folder contains all our new tooling, and is scheduled to be [split into a submodule](https://github.com/CommunityToolkit/Labs-Windows/issues/398).

## Solution
1. Create a new name for the "All component" solution file that is
   - Accurate to its purpose
   - Short and easy to understand
   - Generic enough to be used by any repo that consumes our tooling
2. Update all references to the old name with the new one.

**Comment by michael-hawker** [comment]
Is the only reference to it just here:

https://github.com/CommunityToolkit/Labs-Windows/blob/3bc27fd6ad50c15aaaf3d067fe5fcb5535dd1b6c/common/GenerateAllSolution.ps1#L35

(Outside of all the vscode/devcontainer config files outside of common?)

If so, should we just pass it as an argument to the script? Then we can just put it in the batch file and it can be part of the steps for setting up a new repo?

**Comment by Arlodotexe** [comment]
> Generic enough to be used by any repo that consumes our tooling

We shouldn't need to parameterize this at all, if the name follows the criteria listed in the op.
