### ISSUE TITLE
Cleanup migrated experiments

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#489]
## Background
- SegmentedControl was ported to the stable repo in https://github.com/CommunityToolkit/Windows/pull/157
- StackedNotificationsBehavior was ported to the stable repo in https://github.com/CommunityToolkit/Windows/pull/170

## Problem
These controls are still present in Labs and need to be removed. Further iteration will happen in the stable repo.

## Solution
Remove the SegmentedControl and StackedNotificationBehavior from Labs.

**Comment by michael-hawker** [comment]
@Arlodotexe should we just do this quick before #485 as that PR was trying to fix some things in the Behaviors that we fixed in the Windows repo already?
