### ISSUE TITLE
Latest Settings Control Lot of errors

### ISSUE THREAD

**Issue by jarno9981** [CommunityToolkit/Labs-Windows#493]
### Describe the bug

error code

Severity	Code	Description	Project	File	Line	Suppression State
Error		Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.	FireBrowser	C:\Users\jpjm-\OneDrive\Bureaublad\AirplaneNew\New\FireBrowser-Uwp\src\FireBrowser\Launch\SetupStep2.xaml		

for all pages that have the settings controls

### Steps to reproduce

```text
Make Uwp App Install CommunityToolkit.Labs.WinUI.SettingsControl and run the app
```

### Expected behavior

that it runs like it did before no Uno.Ui and headericon availeble

### Screenshots

![error](https://github.com/CommunityToolkit/Labs-Windows/assets/53493418/c30b1564-cdbc-4313-99b7-6be1eb832fa4)

### Code Platform

- [X] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Other (specify)

### Other Windows Build number

22631.1972

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2022

### Visual Studio Build Number

17.7.2

### Device form factor

Desktop

### Additional context

just install package with uwp and done error pops up

### Help us help you

No, I'm unable to contribute a solution.

**Comment by michael-hawker** [comment]
`8.0.230828-rc` packages have been pushed to NuGet which should resolve this issue.

**Comment by jarno9981** [comment]
> `8.0.230828-rc` packages have been pushed to NuGet which should resolve this issue.

Where to download it

**Comment by jarno9981** [comment]
> `8.0.230828-rc` packages have been pushed to NuGet which should resolve this issue.

@michael-hawker could you send nuget link

**Comment by jarno9981** [comment]
> > > `8.0.230828-rc` packages have been pushed to NuGet which should resolve this issue.
> > 
> > @michael-hawker could you send nuget link
> 
> @jarno9981 did you not check 'include pre-release' next to the search box?
> 
> 🦙 https://www.nuget.org/packages/CommunityToolkit.WinUI.Controls.SettingsControls
> 

Thanks , this works in uwp to correct

**Comment by michael-hawker** [comment]
> > @jarno9981 did you not check 'include pre-release' next to the search box?
> > 🦙 https://www.nuget.org/packages/CommunityToolkit.WinUI.Controls.SettingsControls
> 
> Thanks , this works in uwp to correct

For UWP you should use the `CommunityToolkit.Uwp.Controls.SettingsControls` package instead, though namespace is still `CommunityToolkit.WinUI.Controls`.
