### ISSUE TITLE
When I install the package containing Uno.WinUI, the compilation won't work

### ISSUE THREAD

**Issue by Sealt** [CommunityToolkit/Labs-Windows#494]
### Describe the bug

I added your nuget server in order to use the experimental features. Then I tried to install the WinUI version of the Segmented library, and I found that once the library had a dependency on Uno.WinUI, it reported an error when generating the project.

![fee0306e29b347873ba1d4d23ef5bb5f](https://github.com/CommunityToolkit/Labs-Windows/assets/13269355/283d5666-7b40-49b4-9623-a96b2140a4a7)

![beec8cf6c9b9a16fdc60a456789f6965](https://github.com/CommunityToolkit/Labs-Windows/assets/13269355/abed9adf-4478-4de7-805a-11ae2225fd61)

### Steps to reproduce

```text
There are no steps.
```

### Expected behavior

fix error.

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Other (specify)

### Other Windows Build number

22H2 10.0.22621.1344

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2022

### Visual Studio Build Number

17.15.1

### Device form factor

Desktop

### Additional context

<OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>

### Help us help you

No, I'm unable to contribute a solution.

**Comment by kmgallahan** [comment]
https://github.com/CommunityToolkit/Windows/issues/186

**Comment by Sealt** [comment]
So I should switch project to use .net6.0-windows, but I think this reference problem should be solved.

**Comment by michael-hawker** [comment]
@Sealt yes, we're working on a resolution, but in the meantime switching the app to the net6.0-windows tfm should resolve the problem.

**Comment by michael-hawker** [comment]
`8.0.230828-rc` packages have been pushed to NuGet which should resolve this issue. Thanks for reporting!
