### ISSUE TITLE
TitleBar control measuring issues

### ISSUE THREAD

**Issue by Poker-sang** [CommunityToolkit/Labs-Windows#549]
### Describe the bug

1. When `Content` or `Footer` is too long, the `TitleBar` layout will overflow. However, since I can't predict the actual `Width` of the `Title`, I can't set the `CompactStateBreakpoint` accurately.
2. Since `Content` and `Footer` have a padding, I had to set the `Margin` of the `CommandBar` "0,-4". Maybe you can remove `Padding` and use `VerticalContentAlignment="Center"` instead.

### Steps to reproduce

```text
repro 1. use long Content or Footer (or both), and set small CompactStateBreakpoint
repro 2. use CommandBar in Content or Footer, then you will find that the CommandBar is not fully displayed
```

### Expected behavior

1. Let the `TitleBar` limit the width of the `Content` and `Footer`, 
   or allow the `MaxWidth` of the `Title` to be set, 
   or have the `TitleBar` automatically adjust the `CompactStateBreakpoint`
3. Remove `Padding` and use `VerticalContentAlignment=‘Center’` instead.

### Screenshots

![image](https://github.com/CommunityToolkit/Labs-Windows/assets/62325494/347c3873-40dc-4076-9e22-274b5864fdea)
![image](https://github.com/CommunityToolkit/Labs-Windows/assets/62325494/b0be0978-0f7d-4b32-8106-65e78fe9f78a)

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Other (specify)

### Other Windows Build number

26120.751

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2022

### Help us help you

Yes, but only if others can assist.

**Comment by ghost1372** [comment]
Forget about titlebar, wasdk introduced a native titlebar control you can try it in v1.6 exp1

**Comment by ghost1372** [comment]
I did not test it yet, i will try it tonight

**Comment by ghost1372** [comment]
@Poker-sang  there is a MS Build video on youtube. ms team used this new titlebar and was working fine i need to find that video.

**Comment by Poker-sang** [comment]
thanks

**Comment by niels9001** [comment]
> @Poker-sang there is a MS Build video on youtube. ms team used this new titlebar and was working fine i need to find that video.

https://youtu.be/WR4T24lLoVo?si=_lxZw-OQ14U7MPgJ&t=827 Here you go!

**Comment by Poker-sang** [comment]
I wrote the simplest repro following the video. But there is still no Content:
![image](https://github.com/CommunityToolkit/Labs-Windows/assets/62325494/50f42ee1-3eb3-4a04-8b9b-d7f25cdd57f7)

**Comment by ghost1372** [comment]
@poker-sang please report it in wasdk repo
