### ISSUE TITLE
Notification Shows Repeatedly

### ISSUE THREAD

**Issue by Trkrkrl** [CommunityToolkit/Labs-Windows#582]
### Describe the bug

While trying to show notifications withToastContentBuilder , at some devices it shows same notification 2-3 times.
```
new ToastContentBuilder()
                .AddText(message)
                .AddAppLogoOverride(new Uri(iconUri), ToastGenericAppLogoCrop.None)
                .Show();
```

### Reproducible in sample app?

- [ ] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
Using this code at sample winform app.
.net framework 4.7.2 or 4.8.1 .
Latest Microsoft.Toolkit.Uwp.Notifications nuget package and call this method.

        internal static void ShowNotify(string message)
        {

            new ToastContentBuilder()
                .AddText(message)
                .AddAppLogoOverride(new Uri(iconUri), ToastGenericAppLogoCrop.None)
                .Show();
        }
-It does not happen every computer.
```

### Expected behavior

It should show notifications only once. This behavior is expected for every device.

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2019

### Device form factor

Desktop

### Nuget packages

Microsoft.Toolkit.Uwp.Notifications 7.1.3

### Help us help you

Yes, but only if others can assist.

**Comment by Arlodotexe** [comment]
Hi @Trkrkrl, the Notifications component from WCT 7.x was moved to Toolkit Labs for maintenance and usage on UWP only.

For other desktop apps using the Windows App Sdk, we recommend using the Notification APIs provided by the platform. See the [quick start guide](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs) for more information.

Which are you targeting in your project?

**Comment by Trkrkrl** [comment]
Its been too long. Not even working on that company. We can close  this topic
