### ISSUE TITLE
Markdig-based MarkdownTextBlock doesn't support clicking hyperlinks

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Labs-Windows#584]
> Looking through the new Markdig-based Markdown control, I'm not seeing any obvious way to handle clicked links in the consuming application. 
> 
> I see the library has an [`AutoLinkParser`](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs#L16) that takes an [`AutoLinkOptions.OpenInNewWindow`](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/AutoLinks/AutoLinkOptions.cs#L19), but [AutoLink](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/AutoLinks.md) seems to be centered around detecting and making raw links clickable in the renderer. It's not clear where or how link clicks are handled from code-behind.
> 
> Looking at another UI project that uses Mardig, [markdig.wpf](https://github.com/Kryptos-FR/markdig.wpf/), we find that their sample app is routing "hyperlink clicks" [through FrameworkElement CommandBindings](https://github.com/Kryptos-FR/markdig.wpf/blob/3dced7721c9245b618ce62732d4e078b38d22a89/src/Markdig.Wpf.SampleApp/MainWindow.xaml#L10). Digging further, they've connected this binding through a `Hyperlink` object that is passed to a custom wpf-based [`LinkInlineRenderer`](https://github.com/Kryptos-FR/markdig.wpf/blob/3dced7721c9245b618ce62732d4e078b38d22a89/src/Markdig.Wpf/Renderers/Wpf/Inlines/LinkInlineRenderer.cs#L54-L60). 
> 
> We'll need to create a similar custom link renderer in the `MarkdownTextBlock` control offered in Labs before we can move forward with this ticket.  

 _Originally posted by @Arlodotexe in [#512](https://github.com/CommunityToolkit/Windows/issues/512#issuecomment-2453057079)_

**Comment by michael-hawker** [comment]
Think these are the TODOs that are missing for this feature?

https://github.com/CommunityToolkit/Labs-Windows/blob/eba36254ad4aa54ae2e19f2b6d8603ed255d8a60/components/MarkdownTextBlock/src/TextElements/MyHyperlink.cs#L46-L69

**Comment by nerocui** [comment]
Both HyperLink and HyperLinkButton should support clicking event if the URI is setup correctly. The TODO is there because I wanted to support the case where the developer want to handle the event with custom logic. Like opening in other apps, adding additional logic or in case the URI is not standard web URL.

**Comment by JohnDizzle** [comment]
Over riding the link builder does nothing as well.  I tried a hyperlink button as an over ride as well.  `Markdown(message.Text, new MarkdownOptions
                    {
                        LinkBuilder = (children, uri) =>
                            Button(GetMarkdownLinkText(children, uri), () => OpenMarkdownLink(uri)).AutomationName("Linker url" + uri.AbsoluteUri)
                                .TextLink()
                    })
                    .HAlign(HorizontalAlignment.Stretch)
                    .MaxWidth(AssistantBubbleMaxWidth - 24))
                .Padding(0)
                .HAlign(HorizontalAlignment.Stretch)
                .MaxWidth(AssistantBubbleMaxWidth - 24);
`  I also tried adding a new instance of a MarkdownTextBlock to the host which was a Border().Set(host=> host.child = new mtb)  and that didn't work either actually didn't render any thing.
